docker:
  only:
    - master 
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_HUB_USER/cdk8s -f Dockerfile.typescript .
    - docker build -t $DOCKER_HUB_USER/cdk8s:python -f Dockerfile.python .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USER/cdk8s
    - docker push $DOCKER_HUB_USER/cdk8s:python
